name: Apickli Shell Pipeline
on: workflow_dispatch
jobs:
  example-project:
    name: Example Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run in docker
      uses: ./example-project
